"""
SQLite DAO for the AnimaDex-derived character and artist catalogues.

Databases are generated by scripts/import_anima.py from the animadex.net
offline export. The UI fetches cover images on-demand from
https://blobs.animadex.net and caches them locally.
"""
from __future__ import annotations

import sqlite3
from pathlib import Path
from typing import Any

_R2_BASE = "https://blobs.animadex.net"
_CHAR_THUMB_PREFIX = "Outputs/thumbs"
_CHAR_IMG_PREFIX = "Outputs"
_ARTIST_THUMB_PREFIX = "ArtistOutputs/thumbs"
_ARTIST_IMG_PREFIX = "ArtistOutputs"

_anima_character_db: "AnimaCharacterDB | None" = None
_anima_artist_db: "AnimaArtistDB | None" = None


def _get_db_path(name: str) -> Path:
    repo_root = Path(__file__).resolve().parent.parent
    return repo_root / "data" / name


def get_anima_character_db() -> "AnimaCharacterDB":
    global _anima_character_db
    if _anima_character_db is None:
        _anima_character_db = AnimaCharacterDB(_get_db_path("anima_characters.db"))
    return _anima_character_db


def get_anima_artist_db() -> "AnimaArtistDB":
    global _anima_artist_db
    if _anima_artist_db is None:
        _anima_artist_db = AnimaArtistDB(_get_db_path("anima_artists.db"))
    return _anima_artist_db


def _r2_quote(name: str) -> str:
    """Quote an R2 object name while preserving the characters the UI/URLs need.

    AnimaDex stores thumbnail filenames derived from the trigger, e.g.
    ``2b (nier_automata), nier (series).webp``.  R2 accepts the raw spaces and
    commas, so we keep them unescaped to keep URLs readable.
    """
    from urllib.parse import quote

    return quote(name, safe="(),")


def character_thumb_url(thumbname: str) -> str:
    return f"{_R2_BASE}/{_CHAR_THUMB_PREFIX}/{_r2_quote(thumbname)}"


def character_image_url(imgname: str) -> str:
    return f"{_R2_BASE}/{_CHAR_IMG_PREFIX}/{_r2_quote(imgname)}"


def artist_thumb_url(thumbname: str) -> str:
    return f"{_R2_BASE}/{_ARTIST_THUMB_PREFIX}/{_r2_quote(thumbname)}"


def artist_image_url(imgname: str) -> str:
    return f"{_R2_BASE}/{_ARTIST_IMG_PREFIX}/{_r2_quote(imgname)}"


class AnimaCharacterDB:
    def __init__(self, path: Path):
        self.path = path
        self._ensure_exists()

    def _ensure_exists(self):
        if not self.path.exists():
            raise FileNotFoundError(
                f"Anima character database not found at {self.path}. "
                "Run: python scripts/import_anima.py --token YOUR_TOKEN"
            )

    def _connect(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.path)
        conn.row_factory = sqlite3.Row
        return conn

    def count(self, query: str = "") -> int:
        with self._connect() as conn:
            if query:
                sql = "SELECT COUNT(*) FROM characters WHERE search_blob LIKE ?"
                params = (f"%{query}%",)
            else:
                sql = "SELECT COUNT(*) FROM characters"
                params = ()
            return conn.execute(sql, params).fetchone()[0]

    def search(
        self,
        query: str = "",
        copyright: str | None = None,
        limit: int = 24,
        offset: int = 0,
    ) -> list[dict[str, Any]]:
        with self._connect() as conn:
            conditions = []
            params: list[Any] = []
            if query:
                conditions.append("search_blob LIKE ?")
                params.append(f"%{query}%")
            if copyright:
                conditions.append("copyright = ?")
                params.append(copyright)
            where = "WHERE " + " AND ".join(conditions) if conditions else ""
            sql = (
                f"SELECT * FROM characters {where} "
                "ORDER BY count DESC, name LIMIT ? OFFSET ?"
            )
            params.extend([limit, offset])
            rows = conn.execute(sql, params).fetchall()
            return [dict(r) for r in rows]

    def get_by_character(self, character: str) -> dict[str, Any] | None:
        with self._connect() as conn:
            row = conn.execute(
                "SELECT * FROM characters WHERE character = ?", (character,)
            ).fetchone()
            return dict(row) if row else None

    def list_copyrights(self, limit: int = 100) -> list[dict[str, Any]]:
        with self._connect() as conn:
            rows = conn.execute(
                "SELECT copyright, COUNT(*) AS n FROM characters "
                "WHERE copyright IS NOT NULL AND copyright != '' "
                "GROUP BY copyright ORDER BY n DESC LIMIT ?",
                (limit,),
            ).fetchall()
            return [dict(r) for r in rows]


class AnimaArtistDB:
    def __init__(self, path: Path):
        self.path = path
        self._ensure_exists()

    def _ensure_exists(self):
        if not self.path.exists():
            raise FileNotFoundError(
                f"Anima artist database not found at {self.path}. "
                "Run: python scripts/import_anima.py --token YOUR_TOKEN"
            )

    def _connect(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.path)
        conn.row_factory = sqlite3.Row
        return conn

    def count(self, query: str = "") -> int:
        with self._connect() as conn:
            if query:
                sql = "SELECT COUNT(*) FROM artists WHERE search_blob LIKE ?"
                params = (f"%{query}%",)
            else:
                sql = "SELECT COUNT(*) FROM artists"
                params = ()
            return conn.execute(sql, params).fetchone()[0]

    def search(
        self,
        query: str = "",
        limit: int = 24,
        offset: int = 0,
    ) -> list[dict[str, Any]]:
        with self._connect() as conn:
            if query:
                sql = (
                    "SELECT * FROM artists WHERE search_blob LIKE ? "
                    "ORDER BY count DESC, name LIMIT ? OFFSET ?"
                )
                params = (f"%{query}%", limit, offset)
            else:
                sql = "SELECT * FROM artists ORDER BY count DESC, name LIMIT ? OFFSET ?"
                params = (limit, offset)
            rows = conn.execute(sql, params).fetchall()
            return [dict(r) for r in rows]

    def get_by_artist(self, artist: str) -> dict[str, Any] | None:
        with self._connect() as conn:
            row = conn.execute(
                "SELECT * FROM artists WHERE artist = ?", (artist,)
            ).fetchone()
            return dict(row) if row else None
