#!/usr/bin/env python3
"""Fetch a small, resumable batch of categorized e621 post evidence.

This script consumes the prioritized review CSV generated by
``audit_e621_series.py`` and queries only rows marked ``post_api``. It does not
change the catalogue or the tracked implication evidence. Results are cached
under ``data/generated`` for human review and later promotion into audited
catalogue decisions.
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import sys
import time
from pathlib import Path
from typing import Any

import requests


REPO_ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = REPO_ROOT / "data"
DEFAULT_REVIEW_CSV = DATA_DIR / "generated" / "e621_series_review.csv"
DEFAULT_CACHE = DATA_DIR / "generated" / "e621_post_samples.json"
DEFAULT_API_URL = "https://e621.net/posts.json"
DEFAULT_USER_AGENT = (
    "SDCharacterFinder/0.6.2 "
    "(by eduardoabreu81; offline character catalogue audit)"
)
CACHE_SCHEMA_VERSION = 1


class E621PostEvidenceError(RuntimeError):
    """Raised when a post-evidence batch cannot be completed safely."""


def _write_json_atomic(path: Path, data: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix(path.suffix + ".tmp")
    temporary.write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    os.replace(temporary, path)


def read_queue(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        raise E621PostEvidenceError(f"Review queue not found: {path}")
    with path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.DictReader(handle)
        required = {
            "audit_status",
            "source_record_id",
            "resolved_tag",
            "source_tag_raw",
            "source_name_raw",
            "post_count",
            "current_series_raw",
            "prompt_sha256",
        }
        missing = required.difference(reader.fieldnames or [])
        if missing:
            raise E621PostEvidenceError(
                f"Review queue is missing columns: {sorted(missing)}"
            )
        return [row for row in reader if row["audit_status"] == "post_api"]


def read_cache(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {
            "schema_version": CACHE_SCHEMA_VERSION,
            "provider": "e621_posts_api",
            "samples": [],
        }
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise E621PostEvidenceError(f"Cannot read post evidence cache: {path}") from exc
    if (
        not isinstance(data, dict)
        or data.get("schema_version") != CACHE_SCHEMA_VERSION
        or data.get("provider") != "e621_posts_api"
        or not isinstance(data.get("samples"), list)
    ):
        raise E621PostEvidenceError(f"Invalid post evidence cache: {path}")
    return data


def extract_post_sample(
    queue_row: dict[str, str],
    response_body: dict[str, Any],
) -> dict[str, Any]:
    posts = response_body.get("posts")
    if not isinstance(posts, list):
        raise E621PostEvidenceError("e621 response does not contain a posts list")
    if not posts:
        return {
            "source_record_id": int(queue_row["source_record_id"]),
            "resolved_tag": queue_row["resolved_tag"],
            "source_tag_raw": queue_row["source_tag_raw"],
            "source_name_raw": queue_row["source_name_raw"],
            "current_series_raw": queue_row["current_series_raw"],
            "known_post_count": int(queue_row["post_count"]),
            "prompt_sha256": queue_row["prompt_sha256"],
            "sample_status": "no_post_returned",
            "post_id": None,
            "copyright_tags": [],
            "character_tags": [],
        }

    post = posts[0]
    tags = post.get("tags") if isinstance(post, dict) else None
    if not isinstance(tags, dict):
        raise E621PostEvidenceError("e621 post does not contain categorized tags")
    copyright_tags = tags.get("copyright", [])
    character_tags = tags.get("character", [])
    if not isinstance(copyright_tags, list) or not isinstance(character_tags, list):
        raise E621PostEvidenceError("e621 post tag categories have an invalid shape")
    return {
        "source_record_id": int(queue_row["source_record_id"]),
        "resolved_tag": queue_row["resolved_tag"],
        "source_tag_raw": queue_row["source_tag_raw"],
        "source_name_raw": queue_row["source_name_raw"],
        "current_series_raw": queue_row["current_series_raw"],
        "known_post_count": int(queue_row["post_count"]),
        "prompt_sha256": queue_row["prompt_sha256"],
        "sample_status": (
            "single_copyright"
            if len(copyright_tags) == 1
            else "multiple_copyrights"
            if copyright_tags
            else "no_copyright"
        ),
        "post_id": int(post["id"]),
        "copyright_tags": sorted(str(tag) for tag in copyright_tags),
        "character_tags": sorted(str(tag) for tag in character_tags),
    }


def fetch_batch(
    queue_path: Path,
    cache_path: Path,
    *,
    limit: int,
    rate_limit: float,
    api_url: str,
    user_agent: str,
    session: requests.Session | None = None,
) -> dict[str, Any]:
    if limit < 1:
        raise E621PostEvidenceError("Batch limit must be at least 1")
    if rate_limit < 1.0:
        raise E621PostEvidenceError("Sustained e621 requests must be spaced by >= 1s")

    queue = read_queue(queue_path)
    cache = read_cache(cache_path)
    existing_tags = {
        str(row.get("resolved_tag"))
        for row in cache["samples"]
        if isinstance(row, dict)
    }
    pending = [row for row in queue if row["resolved_tag"] not in existing_tags][:limit]
    http = session or requests.Session()
    http.headers.update(
        {
            "User-Agent": user_agent,
            "Accept": "application/json",
        }
    )

    for index, row in enumerate(pending):
        try:
            response = http.get(
                api_url,
                params={"tags": row["resolved_tag"], "limit": 1},
                timeout=30,
            )
            response.raise_for_status()
            body = response.json()
        except (requests.RequestException, ValueError) as exc:
            raise E621PostEvidenceError(
                f"e621 request failed for {row['resolved_tag']}: {exc}"
            ) from exc
        sample = extract_post_sample(row, body)
        sample["post_url"] = (
            f"https://e621.net/posts/{sample['post_id']}"
            if sample["post_id"] is not None
            else None
        )
        cache["samples"].append(sample)
        _write_json_atomic(cache_path, cache)
        print(
            f"[{index + 1}/{len(pending)}] {row['resolved_tag']}: "
            f"{sample['sample_status']}"
        )
        if index + 1 < len(pending):
            time.sleep(rate_limit)

    cache["summary"] = {
        "queue_total": len(queue),
        "cached_total": len(cache["samples"]),
        "remaining": max(0, len(queue) - len(cache["samples"])),
    }
    _write_json_atomic(cache_path, cache)
    return cache


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--review-csv", type=Path, default=DEFAULT_REVIEW_CSV)
    parser.add_argument("--cache", type=Path, default=DEFAULT_CACHE)
    parser.add_argument("--limit", type=int, default=25)
    parser.add_argument("--rate-limit", type=float, default=1.0)
    parser.add_argument("--api-url", default=DEFAULT_API_URL)
    parser.add_argument("--user-agent", default=DEFAULT_USER_AGENT)
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    try:
        cache = fetch_batch(
            args.review_csv.resolve(),
            args.cache.resolve(),
            limit=args.limit,
            rate_limit=args.rate_limit,
            api_url=args.api_url,
            user_agent=args.user_agent,
        )
    except E621PostEvidenceError as exc:
        print(f"e621 post evidence failed: {exc}", file=sys.stderr)
        return 1

    summary = cache["summary"]
    print(f"Cache: {args.cache.resolve()}")
    print(
        f"Post evidence: {summary['cached_total']:,} cached, "
        f"{summary['remaining']:,} remaining"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
